

services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: demo_container_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  app:
    depends_on:
      - postgres
    build: ./
    container_name: demo_container_app
    restart: on-failure
    ports:
      - 2025:2025
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/postgres?currentSchema=public",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "root",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.rabbitmq.port": "5672",
        "spring.rabbitmq.username": "guest",
        "spring.rabbitmq.password": "guest"
      }'
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    stdin_open: true
    tty: true

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    restart: always
    depends_on:
      - postgres
    # Load environment variables
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=root
      - FLYWAY_SCHEMAS=public
      - FLYWAY_BASELINE-ON-MIGRATE=true
      - FLYWAY_GROUP=true
    # Mount the migrations directory
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    # Run Flyway migrations
    entrypoint: [ "flyway", "migrate" ]
